<template>
  <div class="mx-auto max-w-7xl p-5 lg:p-8">
    <div class="mb-7"><p class="text-sm font-semibold text-[#1f7994]">زیرساخت هوش مصنوعی</p><h1 class="mt-1 text-2xl font-bold text-[#093544]">Providerهای هوش مصنوعی</h1><p class="mt-2 max-w-3xl text-sm text-[#61757d]">هر اتصال مدل و کلید مستقل دارد. اتصال پیش‌فرض در تمام ابزارهای هوش مصنوعی پنل استفاده خواهد شد.</p></div>
    <div v-if="error" role="alert" class="mb-5 flex flex-wrap items-center justify-between gap-3 border-s-2 border-[#c33] bg-[#fff2f2] px-4 py-3 text-sm text-[#a32626]"><span>{{ error }}</span><button type="button" class="retry" @click="load">تلاش مجدد</button></div>
    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_25rem]">
      <section class="border border-[#d4e0e4] bg-white p-5">
        <div class="mb-5 flex items-center justify-between"><div><h2 class="font-bold text-[#093544]">اتصال‌های ساخته‌شده</h2><p class="mt-1 text-sm text-[#61757d]">کلید API پس از ذخیره قابل نمایش یا بازیابی نیست.</p></div><span class="text-xs text-[#61757d]">{{ configs.length }} مورد</span></div>
        <p v-if="pending" class="py-8 text-sm text-[#61757d]">در حال دریافت تنظیمات…</p>
        <div v-else class="space-y-3"><article v-for="config in configs" :key="config.id" class="border border-[#d4e0e4] p-4" :class="{ 'border-[#1f7994] bg-[#f4fbfc]': config.isDefault }"><div class="flex flex-wrap items-start justify-between gap-3"><div><div class="flex items-center gap-2"><h3 class="font-bold text-[#093544]">{{ config.name }}</h3><span v-if="config.isDefault" class="bg-[#1f7994] px-2 py-0.5 text-xs font-semibold text-white">پیش‌فرض</span><span v-if="!config.enabled" class="bg-[#edf1f2] px-2 py-0.5 text-xs text-[#61757d]">غیرفعال</span></div><p dir="ltr" class="mt-2 text-xs text-[#61757d]">{{ config.provider }} · {{ config.model }}</p><p dir="ltr" class="mt-1 break-all text-xs text-[#61757d]">{{ config.baseUrl }}</p><p v-if="testResults[config.id]" class="mt-2 text-xs" :class="testResults[config.id].ok ? 'text-[#087443]' : 'text-[#a32626]'">{{ testResults[config.id].message }}</p></div><div v-if="canEdit" class="flex flex-wrap gap-2"><button class="action" :disabled="testingId === config.id" @click="test(config.id)">{{ testingId === config.id ? 'در حال تست…' : 'تست اتصال' }}</button><button class="action" @click="edit(config)">ویرایش</button><button v-if="!config.isDefault" class="action" @click="setDefault(config.id)">پیش‌فرض</button><button class="danger" @click="remove(config.id)">حذف</button></div></div></article><p v-if="!configs.length" class="py-8 text-center text-sm text-[#61757d]">هنوز اتصالی ساخته نشده است.</p></div>
      </section>
      <section class="border border-[#d4e0e4] bg-white p-5"><div class="mb-5"><h2 class="font-bold text-[#093544]">{{ editingId ? 'ویرایش اتصال' : 'افزودن اتصال' }}</h2><p class="mt-1 text-sm text-[#61757d]">ابتدا Provider و نشانی API را مشخص کنید، سپس فهرست مدل‌ها را دریافت کنید.</p></div><form class="space-y-4" @submit.prevent="save"><label>نام این اتصال<input v-model="form.name" :disabled="!canEdit" class="field" placeholder="مثلاً مدل محتوای فارسی"></label><label>Provider<select v-model="form.provider" :disabled="!canEdit" class="field" @change="applyProvider"><option v-for="provider in catalog" :key="provider.id" :value="provider.id">{{ provider.label }}</option></select></label><label>نشانی API / Base URL<input v-model="form.baseUrl" :disabled="!canEdit" dir="ltr" class="field" placeholder="https://…/v1"></label><label>کلید API <span v-if="editingId" class="text-xs font-normal text-[#61757d]">(برای حفظ کلید فعلی خالی بگذارید)</span><input v-model="form.apiKey" :required="!editingId" :disabled="!canEdit" type="password" dir="ltr" autocomplete="new-password" class="field"></label><div class="flex flex-wrap items-end gap-2"><label class="min-w-[12rem] flex-1">مدل استخراج‌شده<select v-model="form.model" :disabled="!canEdit || !models.length" class="field"><option value="">انتخاب از فهرست</option><option v-for="model in models" :key="model.id" :value="model.id">{{ model.label }}</option></select></label><button type="button" :disabled="!canEdit || extracting || !form.baseUrl || !form.apiKey" class="secondary" @click="extractModels">{{ extracting ? 'در حال دریافت…' : 'استخراج مدل‌ها' }}</button></div><label>نام مدل (دستی یا از فهرست)<input v-model="form.model" :disabled="!canEdit" required dir="ltr" class="field" placeholder="gpt-4.1-mini"></label><p v-if="models.length" class="text-xs text-[#087443]">{{ models.length }} مدل قابل انتخاب دریافت شد.</p><label class="checkbox-label text-sm"><input v-model="form.enabled" :disabled="!canEdit" type="checkbox" class="h-4 w-4 shrink-0 accent-[#1f7994]"><span>اتصال فعال باشد</span></label><label class="checkbox-label text-sm"><input v-model="form.isDefault" :disabled="!canEdit" type="checkbox" class="h-4 w-4 shrink-0 accent-[#1f7994]"><span>مدل پیش‌فرض سراسری باشد</span></label><div v-if="canEdit" class="flex gap-2"><button class="save" type="submit">{{ editingId ? 'ذخیره تغییرات' : 'ساخت اتصال' }}</button><button v-if="editingId" class="secondary" type="button" @click="reset">انصراف</button></div></form></section>
    </div>
  </div>
</template>
<script setup lang="ts">
defineI18nRoute(false)
definePageMeta({ name: 'admin-ai-providers___fa', layout: 'admin', middleware: 'admin' })
const { request } = useCmsApi(); const { user } = useCmsSession()
const pending = ref(true); const extracting = ref(false); const testingId = ref(''); const error = ref(''); const configs = ref<any[]>([]); const catalog = ref<any[]>([]); const models = ref<Array<{ id: string; label: string }>>([]); const editingId = ref(''); const testResults = ref<Record<string, { ok: boolean; message: string }>>({})
const empty = () => ({ name: '', provider: 'openai', baseUrl: 'https://api.openai.com/v1', apiKey: '', model: '', enabled: true, isDefault: !configs.value.length })
const form = reactive(empty()); const canEdit = computed(() => user.value?.role !== 'VIEWER')
function reset() { editingId.value = ''; models.value = []; Object.assign(form, empty()) }
function applyProvider() { const selected = catalog.value.find(item => item.id === form.provider); form.baseUrl = selected?.baseUrl || ''; models.value = []; form.model = '' }
async function load() { try { [configs.value, catalog.value] = await Promise.all([request<any[]>('/admin/ai-providers'), request<any[]>('/admin/ai-providers/catalog')]) } catch (cause: any) { error.value = cause?.data?.message || 'دریافت تنظیمات ناموفق بود.' } finally { pending.value = false } }
async function extractModels() { extracting.value = true; error.value = ''; try { const result = await request<any>('/admin/ai-providers/extract-models', { method: 'POST', body: { provider: form.provider, baseUrl: form.baseUrl, apiKey: form.apiKey } }); models.value = result.models; if (!models.value.some(item => item.id === form.model)) form.model = models.value[0]?.id || '' } catch (cause: any) { error.value = cause?.data?.message || 'دریافت مدل‌ها ناموفق بود.' } finally { extracting.value = false } }
async function save() { error.value = ''; try { const saved = await request<any>(editingId.value ? `/admin/ai-providers/${editingId.value}` : '/admin/ai-providers', { method: editingId.value ? 'PUT' : 'POST', body: form }); const index = configs.value.findIndex(item => item.id === saved.id); if (index >= 0) configs.value[index] = saved; else configs.value.unshift(saved); if (saved.isDefault) configs.value.forEach(item => { if (item.id !== saved.id) item.isDefault = false }); reset() } catch (cause: any) { error.value = cause?.data?.message || 'ذخیره اتصال ناموفق بود.' } }
async function test(id: string) { testingId.value = id; error.value = ''; try { const result = await request<any>(`/admin/ai-providers/${id}/test`, { method: 'POST' }); testResults.value[id] = { ok: true, message: `تست واقعی موفق بود (${result.latencyMs} میلی‌ثانیه)` } } catch (cause: any) { testResults.value[id] = { ok: false, message: cause?.data?.message || 'تست اتصال ناموفق بود.' } } finally { testingId.value = '' } }
function edit(config: any) { editingId.value = config.id; models.value = [{ id: config.model, label: config.model }]; Object.assign(form, { ...config, apiKey: '' }) }
async function setDefault(id: string) { try { const saved = await request<any>(`/admin/ai-providers/${id}/default`, { method: 'POST' }); configs.value.forEach(item => item.isDefault = item.id === saved.id) } catch (cause: any) { error.value = cause?.data?.message || 'تنظیم پیش‌فرض ناموفق بود.' } }
async function remove(id: string) { if (!confirm('این اتصال حذف شود؟')) return; try { await request(`/admin/ai-providers/${id}`, { method: 'DELETE' }); configs.value = configs.value.filter(item => item.id !== id); if (editingId.value === id) reset() } catch (cause: any) { error.value = cause?.data?.message || 'حذف اتصال ناموفق بود.' } }
onMounted(load)
</script>
<style scoped>
.field { display:block; width:100%; margin-top:.45rem; border:1px solid #c9d9df; background:#fff; padding:.65rem .75rem; color:#13272e; font-size:.875rem; outline:none; } .field:focus { border-color:#1f7994; box-shadow:0 0 0 2px rgb(31 121 148 / .15); } label { display:block; color:#24434d; font-size:.875rem; font-weight:700; } .checkbox-label { display:flex; align-items:center; gap:.75rem; } .save,.secondary,.action,.danger,.retry { min-height:2.5rem; padding:.45rem .8rem; font-size:.8125rem; font-weight:800; } .save { background:#1f7994; color:#fff; } .secondary,.action,.retry { border:1px solid #1f7994; color:#17677f; } .danger { border:1px solid #d9a7a7; color:#a32626; } button:disabled { cursor:not-allowed; opacity:.55; }
</style>
