<template>
  <div class="mx-auto max-w-5xl p-5 lg:p-8">
    <div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-[#1f7994]">عملیات</p><h1 class="mt-1 text-2xl font-bold text-[#093544]">بایگانی و بازیابی</h1></div><button :disabled="creating" class="min-h-10 bg-[#1f7994] px-4 text-sm font-semibold text-white disabled:opacity-50" @click="createExport">{{ creating ? 'در حال ساخت…' : 'ساخت نسخه پشتیبان' }}</button></div>
    <p v-if="error" role="alert" class="mb-5 border-s-2 border-[#c33] bg-[#fff2f2] px-4 py-3 text-sm text-[#a32626]">{{ error }}</p>
    <section class="border border-[#d4e0e4] bg-white p-5"><h2 class="font-bold text-[#093544]">بررسی پیش از بازیابی</h2><p class="mt-1 text-sm text-[#61757d]">فایل پشتیبان را بارگذاری کنید تا ساختار و تعداد رکوردها بدون اعمال هیچ تغییری بررسی شود.</p><label class="mt-4 inline-flex min-h-10 cursor-pointer items-center border border-[#1f7994] px-4 text-sm font-semibold text-[#1f7994]">انتخاب فایل JSON<input class="hidden" type="file" accept="application/json,.json" @change="dryRun"></label><p v-if="validation" class="mt-4 bg-[#f3f7f8] p-3 text-sm text-[#24434d]">نسخه {{ validation.version }} معتبر است: {{ validation.counts.content }} محتوا، {{ validation.counts.settings }} تنظیم، {{ validation.counts.redirects }} مسیر و {{ validation.counts.media }} رسانه.</p><div v-if="archiveFile && validation" class="mt-4 flex flex-wrap items-center gap-3"><input v-model="confirmation" dir="ltr" class="min-h-10 border border-[#c9d9df] px-3 text-sm" placeholder="RESTORE"><button :disabled="confirmation !== 'RESTORE' || restoring" class="min-h-10 bg-[#b3261e] px-4 text-sm font-semibold text-white disabled:opacity-50" @click="restore">{{ restoring ? 'در حال بازیابی…' : 'اعمال بازیابی' }}</button></div></section>
    <section class="mt-6 overflow-hidden border border-[#d4e0e4] bg-white"><div class="border-b border-[#e5edf0] p-5"><h2 class="font-bold text-[#093544]">نسخه‌های پشتیبان</h2></div><div v-if="pending" class="p-5 text-sm text-[#61757d]">در حال دریافت…</div><div v-else class="overflow-x-auto"><table class="w-full min-w-[560px] text-right text-sm"><tbody class="divide-y divide-[#e5edf0]"><tr v-for="job in jobs" :key="job.id"><td class="px-5 py-4"><p class="font-semibold">{{ date(job.createdAt) }}</p><p class="mt-1 text-xs text-[#61757d]">{{ job.status }}</p></td><td class="px-5 py-4"><button v-if="job.status === 'completed'" class="font-semibold text-[#1f7994]" @click="download(job)">دانلود امن</button><span v-else class="text-xs text-[#61757d]">{{ job.error || 'در حال پردازش' }}</span></td></tr><tr v-if="!jobs.length"><td class="p-8 text-center text-[#61757d]">هنوز نسخه‌ای ساخته نشده است.</td></tr></tbody></table></div></section>
  </div>
</template>
<script setup lang="ts">
defineI18nRoute(false); definePageMeta({ name: 'admin-archive___fa', layout: 'admin', middleware: 'admin' })
const { request } = useCmsApi(); const jobs = ref<any[]>([]); const pending = ref(true); const creating = ref(false); const restoring = ref(false); const error = ref(''); const validation = ref<any>(); const archiveFile = ref<File | null>(null); const confirmation = ref('')
const date = (value: string) => new Intl.DateTimeFormat('fa-IR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
async function load() { try { jobs.value = await request('/admin/exports') } catch (cause: any) { error.value = cause?.data?.message || 'دریافت نسخه‌ها انجام نشد.' } finally { pending.value = false } }
async function createExport() { creating.value = true; error.value = ''; try { await request('/admin/exports', { method: 'POST' }); await load() } catch (cause: any) { error.value = cause?.data?.message || 'ساخت نسخه پشتیبان انجام نشد.' } finally { creating.value = false } }
async function download(job: any) { try { const result = await request<any>(`/admin/exports/${job.id}/download`); window.open(result.url, '_blank', 'noopener') } catch (cause: any) { error.value = cause?.data?.message || 'دریافت فایل انجام نشد.' } }
async function dryRun(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; archiveFile.value = file; confirmation.value = ''; const body = new FormData(); body.append('archive', file); try { validation.value = await request('/admin/restore/dry-run', { method: 'POST', body }) } catch (cause: any) { validation.value = undefined; error.value = cause?.data?.message || 'فایل پشتیبان معتبر نیست.' } }
async function restore() { if (!archiveFile.value || confirmation.value !== 'RESTORE') return; restoring.value = true; try { const body = new FormData(); body.append('archive', archiveFile.value); body.append('confirm', confirmation.value); await request('/admin/restore', { method: 'POST', body }); confirmation.value = ''; await load() } catch (cause: any) { error.value = cause?.data?.message || 'بازیابی انجام نشد.' } finally { restoring.value = false } }
onMounted(load)
</script>
