<template>
  <div class="mx-auto max-w-7xl p-5 lg:p-8">
    <div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><NuxtLink to="/admin/site" class="text-sm font-semibold text-[#1f7994]">بازگشت به مدیریت سایت</NuxtLink><h1 class="mt-2 text-2xl font-bold text-[#093544]">{{ isNew ? 'محتوای ساختاریافتهٔ جدید' : 'ویرایش محتوای ساختاریافته' }}</h1><p class="mt-2 text-sm text-[#61757d]">هر دو زبان باید ساختار یکسان و محتوای کامل داشته باشند.</p></div><div class="flex flex-wrap gap-2"><button v-if="!isNew" class="button" :disabled="pending" @click="preview">پیش‌نمایش امن</button><button v-if="state === 'published'" class="button bg-[#1f7994]" :disabled="pending" @click="createDraft">ایجاد پیش‌نویس جدید</button><button v-if="state === 'draft'" class="button" :disabled="pending" @click="submit">ارسال برای تأیید</button><button v-if="state === 'in_review' && canPublish" class="button bg-[#087443]" :disabled="pending" @click="publish">انتشار</button><button v-if="state === 'draft'" class="button bg-[#1f7994]" :disabled="pending" @click="save">ذخیرهٔ پیش‌نویس</button></div></div>
    <p v-if="error" role="alert" class="mb-5 border-s-2 border-red-700 bg-red-50 px-4 py-3 text-sm text-red-800">{{ error }}</p>
    <form class="grid gap-6 xl:grid-cols-[280px_minmax(0,1fr)]" @submit.prevent="save">
      <aside class="space-y-4 border border-[#d4e0e4] bg-white p-5"><label class="field-label">نوع<select v-model="form.type" :disabled="!isNew" class="field" @change="setFamilyForType"><option v-for="type in types" :key="type" :value="type">{{ contentTypeLabel(type) }}</option></select></label><label class="field-label">خانواده محتوا<select v-model="form.family" class="field"><option v-for="family in families" :key="family" :value="family">{{ familyLabel(family) }}</option></select></label><label class="field-label">گونه<input v-model="form.variant" class="field" dir="ltr"></label><label class="field-label">شناسه داخلی<input v-model="form.slug" :disabled="!isNew" class="field" dir="ltr" pattern="[a-z0-9-]+"></label><label v-if="form.family === 'landing_standard'" class="field-label">مسیر عمومی<input v-model="form.path" class="field" dir="ltr" placeholder="/company/example"></label><label v-if="form.family === 'product'" class="field-label">دسته محصول<select v-model="form.category" class="field"><option v-for="category in categories" :key="category" :value="category">{{ categoryLabel(category) }}</option></select></label><label class="field-label">ترتیب<input v-model.number="form.sortOrder" type="number" class="field"></label><div class="rounded bg-[#f4fafb] p-3 text-xs leading-5 text-[#61757d]">وضعیت: {{ statusLabel(state) }}<br>انتشار فقط پس از تأیید مالک و برای هر دو زبان انجام می‌شود.</div></aside>
      <div class="space-y-6"><section class="border border-[#d4e0e4] bg-white p-5"><h2 class="border-b border-[#e5edf0] pb-3 font-bold text-[#093544]">فارسی</h2><ContentMeta v-model="fa"/><BlockEditor :model-value="fa.blocks" :family="form.family" @update:model-value="updateBlocks('fa', $event)"/></section><section class="english-content border border-[#d4e0e4] bg-white p-5" lang="en"><h2 class="border-b border-[#e5edf0] pb-3 font-bold text-[#093544]">English</h2><ContentMeta v-model="en" english/><BlockEditor :model-value="en.blocks" :family="form.family" @update:model-value="updateBlocks('en', $event)"/></section></div>
    </form>
  </div>
</template>

<script setup lang="ts">
import type { ContentBlock, ContentV2Write } from '@pesaba/cms-contracts'
defineI18nRoute(false)
definePageMeta({ name: 'admin-content-v2-id___fa', alias: ['/admin/site/content/:id'], layout: 'admin', middleware: 'admin' })
type Translation = { title: string; description: string; seoTitle: string; seoDescription: string; blocks: ContentBlock[] }
const ContentMeta = { props: ['modelValue', 'english'], emits: ['update:modelValue'], methods: { set(this: any, key: string, value: string) { this.$emit('update:modelValue', { ...this.modelValue, [key]: value }) } }, template: '<div class="grid gap-4 py-4 md:grid-cols-2"><label class="field-label">عنوان<input :value="modelValue.title" class="field" :dir="english ? \'ltr\' : undefined" @input="set(\'title\', $event.target.value)"></label><label class="field-label">توضیح کوتاه<textarea :value="modelValue.description" class="field" :dir="english ? \'ltr\' : undefined" @input="set(\'description\', $event.target.value)"></textarea></label><label class="field-label">عنوان SEO<input :value="modelValue.seoTitle" class="field" :dir="english ? \'ltr\' : undefined" @input="set(\'seoTitle\', $event.target.value)"></label><label class="field-label">توضیح SEO<textarea :value="modelValue.seoDescription" class="field" :dir="english ? \'ltr\' : undefined" @input="set(\'seoDescription\', $event.target.value)"></textarea></label></div>' }
const route = useRoute(); const { request } = useCmsApi(); const { user } = useCmsSession(); const { contentTypeLabel, statusLabel } = useAdminLabels(); const id = computed(() => String(route.params.id)); const isNew = computed(() => id.value === 'new'); const canPublish = computed(() => user.value?.role === 'OWNER')
const types = ['page', 'product', 'article', 'glossary', 'industry', 'use_case', 'company', 'legal']; const categories = ['data-diodes', 'network-encryption', 'network-switching-filtering', 'telecom-transmission', 'cellular-monitoring', 'bio-monitoring']; const families = ['landing_standard', 'landing_home', 'landing_technology', 'landing_trust', 'landing_firmware', 'product', 'industry', 'use_case', 'article', 'glossary', 'company', 'legal']
const familyLabel = (value: string) => ({ landing_standard: 'صفحه استاندارد', landing_home: 'صفحه خانه', landing_technology: 'صفحه فناوری', landing_trust: 'صفحه اعتماد', landing_firmware: 'صفحه میان‌افزار', product: 'محصول', industry: 'صنعت', use_case: 'کاربرد', article: 'مقاله', glossary: 'واژه‌نامه', company: 'شرکت', legal: 'حقوقی' }[value] || value)
const categoryLabel = (value: string) => ({ 'data-diodes': 'دیودهای داده', 'network-encryption': 'رمزنگاری شبکه', 'network-switching-filtering': 'سوئیچ و فیلترینگ شبکه', 'telecom-transmission': 'انتقال مخابراتی', 'cellular-monitoring': 'پایش سلولی', 'bio-monitoring': 'پایش زیستی' }[value] || value)
const form = reactive<{ type: string; family: ContentV2Write['family']; variant: string; slug: string; path: string; category: string; sortOrder: number; updatedAt: string }>({ type: 'page', family: 'landing_standard', variant: 'standard', slug: '', path: '', category: '', sortOrder: 0, updatedAt: '' }); const state = ref<'draft' | 'in_review' | 'published' | 'archived'>('draft'); const pending = ref(false); const error = ref('')
const blank = (): Translation => ({ title: '', description: '', seoTitle: '', seoDescription: '', blocks: [{ id: 'hero', type: 'hero', eyebrow: '', title: '', copy: '' }] }); const fa = ref<Translation>(blank()); const en = ref<Translation>(blank())
function setFamilyForType() { const map: Record<string, ContentV2Write['family']> = { product: 'product', industry: 'industry', use_case: 'use_case', article: 'article', glossary: 'glossary', company: 'company', legal: 'legal', page: 'landing_standard' }; form.family = map[form.type] }
function copyStructure(source: ContentBlock[], previous: ContentBlock[]) { const known = new Map(previous.map(block => [`${block.id}:${block.type}`, block])); return source.map(block => known.get(`${block.id}:${block.type}`) || structuredClone(block)) }
function updateBlocks(locale: 'fa' | 'en', value: ContentBlock[]) { if (locale === 'fa') { fa.value = { ...fa.value, blocks: value }; en.value = { ...en.value, blocks: copyStructure(value, en.value.blocks) } } else { en.value = { ...en.value, blocks: value }; fa.value = { ...fa.value, blocks: copyStructure(value, fa.value.blocks) } } }
function payload() { return { type: form.type, slug: form.slug, family: form.family, variant: form.variant, ...(form.family === 'landing_standard' ? { path: form.path } : {}), ...(form.family === 'product' ? { category: form.category } : {}), sortOrder: form.sortOrder, translations: [{ locale: 'fa', ...fa.value }, { locale: 'en', ...en.value }] } }
function assign(record: any) { form.type = record.type; form.family = record.family; form.variant = record.variant; form.slug = record.slug; form.path = record.path || ''; form.category = record.category || ''; form.sortOrder = record.sortOrder; form.updatedAt = record.updatedAt || ''; state.value = record.publicationState; const translation = (locale: string) => record.translations.find((item: any) => item.locale === locale); const map = (item: any): Translation => ({ title: item.title, description: item.description, seoTitle: item.seoTitle, seoDescription: item.seoDescription, blocks: item.blocks || [] }); fa.value = map(translation('fa')); en.value = map(translation('en')) }
async function save() { pending.value = true; error.value = ''; try { const record = isNew.value ? await request<any>('/admin/content-v2', { method: 'POST', body: payload() }) : await request<any>(`/admin/content-v2/${id.value}?updatedAt=${encodeURIComponent(form.updatedAt)}`, { method: 'PUT', body: payload() }); assign(record); if (isNew.value) await navigateTo(`/admin/site/content/${record.id}`) } catch (cause: any) { error.value = Array.isArray(cause?.data?.message) ? cause.data.message.join(' ') : cause?.data?.message || cause?.message || 'ذخیره انجام نشد.' } finally { pending.value = false } }
async function submit() { await save(); if (error.value || isNew.value) return; pending.value = true; try { assign(await request<any>(`/admin/content-v2/${id.value}/submit-review`, { method: 'POST' })) } catch (cause: any) { error.value = cause?.data?.message || 'ارسال برای تأیید انجام نشد.' } finally { pending.value = false } }
async function publish() { pending.value = true; error.value = ''; try { assign(await request<any>(`/admin/content-v2/${id.value}/publish`, { method: 'POST' })) } catch (cause: any) { error.value = cause?.data?.message || 'انتشار انجام نشد.' } finally { pending.value = false } }
async function createDraft() { pending.value = true; error.value = ''; try { assign(await request<any>(`/admin/content-v2/${id.value}/create-draft`, { method: 'POST' })) } catch (cause: any) { error.value = cause?.data?.message || 'ایجاد پیش‌نویس انجام نشد.' } finally { pending.value = false } }
async function preview() { pending.value = true; try { const result = await request<{ token: string }>(`/admin/content-v2/${id.value}/preview`, { method: 'POST' }); window.open(`/fa/preview/${id.value}?token=${encodeURIComponent(result.token)}`, '_blank', 'noopener') } catch (cause: any) { error.value = cause?.data?.message || 'ساخت پیش‌نمایش انجام نشد.' } finally { pending.value = false } }
onMounted(async () => { if (isNew.value) return; try { assign(await request(`/admin/content-v2/${id.value}`)) } catch (cause: any) { error.value = cause?.data?.message || 'محتوا پیدا نشد.' } })
</script>

<style scoped>
.button { background:#093544; padding:.65rem .9rem; color:#fff; font-size:.875rem; font-weight:700; }.button:disabled { opacity:.55; }.field { display:block; width:100%; margin-top:.35rem; border:1px solid #c9d9df; background:#fff; padding:.55rem .65rem; color:#13272e; font-size:.875rem; font-weight:400; outline:none; }.field-label { display:block; margin-top:.75rem; font-size:.8125rem; font-weight:700; color:#24434d; }.english-content { direction:ltr; text-align:left; }
</style>
